blogs/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, CommentCreateView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('comment/<int:pk>/', CommentCreateView.as_view(), name='comment')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('products.urls')),
    path('blogs/', include('blogs.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import HomeView, ContactView, ContactCreateView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/create/', ContactCreateView.as_view(), name='contact_create')
]

products/urls.py
from django.urls import path
from .views import ProductListView

app_name = 'products'

urlpatterns = [
    path('products/', ProductListView.as_view(), name='all'),
]

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
          rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}" type="text/css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>
</head>

<body>
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

{% include 'layouts/navbar.html' %}

{% block content %}
{% endblock %}


{% include 'layouts/footer.html' %}
<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form" action="{% url 'products:all' %}">
            <input name="q" value="{{ request.GET.q }}" type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->

<!-- Js Plugins -->
<script src="{% static 'main/js/jquery-3.3.1.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
<script src="{% static 'main/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'main/js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'main/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'main/js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'main/js/jquery.slicknav.js' %}"></script>
<script src="{% static 'main/js/mixitup.min.js' %}"></script>
<script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'main/js/main.js' %}"></script>


{% block extra_js %}
{% endblock %}
</body>

</html>

templates/layouts/footer.html
{% load static %}

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="{% url 'main:home' %}"><img src="{% static 'main/img/footer-logo.png' %}" alt=""></a>
                    </div>
                    <p>The customer is at the heart of our unique business model, which includes design.</p>
                    <a href="#"><img src="{% static 'main/img/payment.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Clothing Store</a></li>
                        <li><a href="#">Trending Shoes</a></li>
                        <li><a href="#">Accessories</a></li>
                        <li><a href="#">Sale</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Payment Methods</a></li>
                        <li><a href="#">Delivary</a></li>
                        <li><a href="#">Return & Exchanges</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                <div class="footer__widget">
                    <h6>NewLetter</h6>
                    <div class="footer__newslatter">
                        <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                        <form action="#">
                            <input type="text" placeholder="Your email">
                            <button type="submit"><span class="icon_mail_alt"></span></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="footer__copyright__text">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <p>Copyright ©
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                        2020
                        All rights reserved | This template is made with <i class="fa fa-heart-o"
                                                                            aria-hidden="true"></i> by <a
                                href="https://colorlib.com" target="_blank">Colorlib</a>
                    </p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
        </div>
    </div>
</footer>

templates/layouts/navbar.html
{% load  static %}
<!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__option">
        <div class="offcanvas__links">
            <a href="#">Sign in</a>
            <a href="#">FAQs</a>
        </div>
        <div class="offcanvas__top__hover">
            <span>Usd <i class="arrow_carrot-down"></i></span>
            <ul>
                <li>USD</li>
                <li>EUR</li>
                <li>USD</li>
            </ul>
        </div>
    </div>
    <div class="offcanvas__nav__option">
        <a href="#" class="search-switch"><img src="{% static 'main/img/icon/search.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'main/img/icon/heart.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'main/img/icon/cart.png' %}" alt=""> <span>0</span></a>
        <div class="price">$0.00</div>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__text">
        <p></p>
    </div>
</div>
<!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                        <p></p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            <a href="#">Sign in</a>
                            <a href="#">Sign up</a>
                        </div>
                        <div class="header__top__hover">
                            <span>eng<i class="arrow_carrot-down"></i></span>
                            <ul>
                                <li>rus</li>
                                <li>uzb</li>
                                <li>smt</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'main:home' %}"><img src="{% static 'main/img/logo.png' %}" alt="logo"></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'main:home' %}">Home</a></li>
                        <li><a href="{% url 'products:all' %}">Shop</a></li>
                        <li><a href="#">Pages</a>
                            <ul class="dropdown">
                                <li><a href="./about.html">About Us</a></li>
                                <li><a href="./shop-details.html">Shop Details</a></li>
                                <li><a href="./shopping-cart.html">Shopping Cart</a></li>
                                <li><a href="./checkout.html">Check Out</a></li>
                                <li><a href="./blog-details.html">Blog Details</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'blogs:list' %}">Blog</a></li>
                        <li><a href="{% url 'main:contact' %}">Contacts</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'main/img/icon/search.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'main/img/icon/heart.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'main/img/icon/cart.png' %}" alt=""> <span>0</span></a>
                    <div class="price">$0.00</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->

templates/layouts/shop_sidebar.html
<div class="shop__sidebar">
    <div class="shop__sidebar__search">
        <form action="{% url 'products:all' %}">
            <input type="text" placeholder="Search..." value="{{ request.GET.q }}" name="q">
            <button type="submit"><span class="icon_search"></span></button>
        </form>
    </div>
    <div class="shop__sidebar__accordion">
        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
                </div>
                <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__categories">
                            <ul class="nice-scroll">
                                {% for category in categories %}
                                    <li>
                                        <a class="{% if category.id|stringformat:'i' == request.GET.cat %}text-dark{% endif %}"
                                           onclick="addSearchParam('cat', {{ category.id }})"
                                           href="#">{{ category.name }}
                                            ({{ category.products.count }})</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
                </div>
                <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__brand">
                            <ul>
                                {% for brand in brands %}
                                    <li>
                                        <a class="{% if brand.id|stringformat:'i' == request.GET.brand %}text-dark{% endif %}"
                                           onclick="addSearchParam('brand', {{ brand.id }})"
                                           href="#">{{ brand.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
                </div>
                <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__price">
                            <input type="text" class="js-range-slider" name="my_range" value="" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseFour">Size</a>
                </div>
                <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__tags">
                            {% for size in sizes %}
                                <a class="{% if size.id|stringformat:'i' == request.GET.size %} bg-dark text-white {% endif %}"
                                   onclick="addSearchParam('size', {{ size.id }})" href="#">{{ size.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseFive">Colors</a>
                </div>
                <div id="collapseFive" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__color">
                            {% for color in colors %}
                                <a href="#" onclick="addSearchParam('color', {{ color.id }})">
                                <label style="background-color: {{ color.code }}" for="sp-1">

                                </label>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
                </div>
                <div id="collapseSix" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__tags">
                            {% for tag in tags %}
                                <a class="{% if tag.id|stringformat:'i' == request.GET.tag %} bg-dark text-white {% endif %}"
                                   onclick="addSearchParam('tag', {{ tag.id }})" href="#">{{ tag.name }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>