blogs/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, CommentCreateView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('comment/<int:pk>/', CommentCreateView.as_view(), name='comment')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('products.urls')),
    path('blogs/', include('blogs.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import HomeView, ContactView, ContactCreateView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/create/', ContactCreateView.as_view(), name='contact_create')
]

blogs/models.py
from django.db import models
from ckeditor.fields import RichTextField
from users.models import UserModel


class BlogTagsModel(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'


class BlogModel(models.Model):
    title = models.CharField(max_length=255)
    body = RichTextField()
    main_image = models.ImageField(upload_to='blogs/')
    banner_image = models.ImageField(upload_to='blogs/')
    tags = models.ManyToManyField(BlogTagsModel, related_name='blogs')
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='blogs')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'
        ordering = ('-id',)


class CommentModel(models.Model):
    name = models.CharField(max_length=120)
    email = models.EmailField()
    phone = models.CharField(max_length=12)
    comment = models.TextField()
    blog = models.ForeignKey(BlogModel, on_delete=models.RESTRICT, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} {self.email}'

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

main/models.py
from django.db import models


class BannerModel(models.Model):
    collection = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    description = models.TextField()
    banner_image = models.ImageField(upload_to='banners/')
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'banner'
        verbose_name_plural = 'banners'


class ContactMessageModel(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

blogs/forms.py
from django import forms
from .models import CommentModel


class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentModel
        exclude = ['blog', 'created_at']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': "Name"}),
            'email': forms.EmailInput(attrs={'placeholder': "Email"}),
            'phone': forms.TextInput(attrs={'placeholder': "Phone"}),
            'comment': forms.Textarea(attrs={'placeholder': "Comment"}),
        }

main/forms.py
from django import forms
from .models import ContactMessageModel


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessageModel
        exclude = ['created_at']
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'name'
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'email'
            }),
            'message': forms.Textarea(attrs={
                'placeholder': 'message'
            }),
        }

blogs/views.py
from django.shortcuts import render, reverse, get_object_or_404
from .models import BlogModel, BlogTagsModel
from django.views.generic import ListView, CreateView, DetailView
from .forms import CommentForm


class BlogListView(ListView):
    template_name = 'blog.html'
    paginate_by = 6

    def get_queryset(self):
        qs = BlogModel.objects.all()
        tag = self.request.GET.get('tag', '')
        if tag:
            qs = qs.filter(tags=tag)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = self.request.GET.get('tag', '')
        if tag:
            context['tag'] = get_object_or_404(BlogTagsModel, pk=tag)

        return context



class BlogDetailView(DetailView):
    template_name = 'blog-details.html'
    model = BlogModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context


class CommentCreateView(CreateView):
    form_class = CommentForm
    template_name = 'blog-details.html'

    def form_valid(self, form):
        blog = get_object_or_404(BlogModel, pk=self.kwargs.get('pk'))
        form.instance.blog = blog
        form.instance.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogs:detail', kwargs={'pk': self.kwargs.get('pk')})

main/views.py
from django.shortcuts import render, reverse
from django.views.generic import TemplateView, CreateView
from .models import BannerModel
from .forms import ContactForm


class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['banners'] = BannerModel.objects.filter(status=True)
        return context


class ContactView(TemplateView):
    template_name = 'contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contact_form'] = ContactForm
        return context


class ContactCreateView(CreateView):
    form_class = ContactForm

    def get_success_url(self):
        return reverse('main:contact')

templates/blog-details.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <!-- Blog Details Hero Begin -->
    <section class="blog-hero spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-9 text-center">
                    <div class="blog__hero__text">
                        <h2>{{ object.title }}</h2>
                        <ul>
                            <li>By {{ object.user.get_full_name }}</li>
                            <li>{{ object.created_at|date:'d F, Y' }}</li>
                            <li>8 Comments</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Hero End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="{{ object.banner_image.url }}" alt="{{ object.title }}">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__share">
                            <span>share</span>
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                                <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <div class="blog__details__text">
                            <p>{{ object.body|safe }}</p>
                        </div>

                        <div class="blog__details__option">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__author">
                                        <div class="blog__details__author__pic">
                                            <img src="{{ object.user.user_image.url }}" alt="{{ object.user }} image">
                                        </div>
                                        <div class="blog__details__author__text">
                                            <h5>{{ object.user.get_full_name }}</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__tags">
                                        {% for tag in object.tags.all %}
                                            <a href="{% url 'blogs:list' %}?tag={{ tag.pk }}">#{{ tag.name }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="blog__details__btns">
                            <div class="row">
                                {% if object.get_previous_by_created_at %}
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <a href="{% url 'blogs:detail' pk=object.get_previous_by_created_at.pk %}"
                                           class="blog__details__btns__item">
                                            <p><span class="arrow_left"></span> Previous Pod</p>
                                            <h5>{{ object.get_previous_by_created_at|truncatewords:5 }}</h5>
                                        </a>
                                    </div>
                                {% endif %}
                            {% if object.get_next_by_created_at %}
                            <div class="col-lg-6 col-md-6 col-sm-6 {% if not object.get_previous_by_created_at %} offset-sm-6 {% endif %}">
                                    <a href="{% url 'blogs:detail' pk=object.get_next_by_created_at.pk %}" class="blog__details__btns__item blog__details__btns__item--next">
                                        <p>Next Pod <span class="arrow_right"></span></p>
                                        <h5>{{ object.get_next_by_created_at|truncatewords:5 }}</h5>
                                    </a>
                                </div>
                            {% endif %}

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                {% for comment in object.comments.values %}
                                    <div>
                                        <strong>{{ comment.name }}</strong>
                                        <div>
                                            <p class="mb-0">{{ comment.comment }}</p>
                                            <small>{{ comment.created_at|timesince }}</small>
                                        </div>
                                    </div>
                                    <hr>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="blog__details__comment">
                            <h4>Leave A Comment</h4>
                            <form action="{% url 'blogs:comment' pk=object.pk %}" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-4 col-md-4">
                                        {{ comment_form.name }}
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        {{ comment_form.email }}
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        {{ comment_form.phone }}
                                    </div>
                                    <div class="col-lg-12 text-center">
                                        {{ comment_form.comment }}
                                        <button type="submit" class="site-btn">Post Comment</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Section End -->
{% endblock %}

templates/blog.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-blog set-bg" data-setbg="{% static 'main/img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {% if tag %}
                        <h2>#{{ tag.name }}</h2>
                        <h4><a href="{% url 'blogs:list' %} " class="text-white">back</a></h4>
                    {% else %}
                        <h2>Our Blog</h2>
                    {% endif %}


                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Blog Section Begin -->
    <section class="blog spad">
        <div class="container">
            <div class="row">
                {% for blog in object_list %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic set-bg" data-setbg="{{ blog.main_image.url }}"></div>
                            <div class="blog__item__text">
                                <span><img src="{% static 'main/img/icon/calendar.png' %}"
                                           alt="">{{ blog.created_at|date:'d F Y' }}</span>
                                <h5>{{ blog.title }}</h5>
                                <a href="{% url 'blogs:detail' pk=blog.pk %}">Read More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        {% if page_obj.paginator.count >= 6 %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="product__pagination">
                        {% for page in page_obj.paginator.page_range %}
                            <a class="{% if page == page_obj.number %}active{% endif %}"
                               href="?page={{ page }}">{{ page }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
    </section>
    <!-- Blog Section End -->
{% endblock %}

templates/contact.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <!-- Map Begin -->
    <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d111551.9926412813!2d-90.27317134641879!3d38.606612219170856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54eab584e432360b%3A0x1c3bb99243deb742!2sUnited%20States!5e0!3m2!1sen!2sbd!4v1597926938024!5m2!1sen!2sbd"
                height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
    <!-- Map End -->

    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="contact__text">
                        <div class="section-title">
                            <span>Information</span>
                            <h2>Contact Us</h2>
                            <p>As you might expect of a company that began as a high-end interiors contractor, we pay
                                strict attention.</p>
                        </div>
                        <ul>
                            <li>
                                <h4>America</h4>
                                <p>195 E Parker Square Dr, Parker, CO 801 <br/>+43 982-314-0958</p>
                            </li>
                            <li>
                                <h4>France</h4>
                                <p>109 Avenue Léon, 63 Clermont-Ferrand <br/>+12 345-423-9893</p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="contact__form">
                        <form action="{% url 'main:contact_create' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-6">
                                    {{ contact_form.name }}
                                </div>
                                <div class="col-lg-6">
                                    {{ contact_form.email }}
                                </div>
                                <div class="col-lg-12">
                                    {{ contact_form.message }}
                                    <button type="submit" class="site-btn">Send Message</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->

{% endblock %}

templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/shop.html
{% extends 'layouts/base.html' %}
{% load static my_tags %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shop</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'main:home' %}">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    {% include 'layouts/shop_sidebar.html' %}
                </div>

                <div class="col-lg-9">
                    <div class="shop__product__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__left">
                                    <p>Showing {{ page_obj.start_index }}–{{ page_obj.end_index }}
                                        of {{ page_obj.paginator.count }} results</p>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__right">
                                    <p>Sort by Price:</p>
                                    <select onchange="addSearchParam('sort', this.value)">
                                        <option value="">-------</option>
                                        <option {% if reques.GET.sort == 'real_price' %}  selected {% endif %}  value="real_price">Low To High</option>
                                        <option {% if reques.GET.sort == '-real_price' %}  selected {% endif %}  value="-real_price">High To Low</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for product in object_list %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product__item sale">
                                    <div class="product__item__pic set-bg"
                                         data-setbg="{{ product.main_image.url }}">
                                        {% if product.is_discount %}
                                            <span class="label">Sale</span>
                                        {% endif %}
                                        {% if product.is_new %}
                                            <span class="label bg-white text-dark{% if product.is_discount %} mt-4 {% endif %}">New</span>
                                        {% endif %}
                                        <ul class="product__hover">
                                            <li><a href="#"><img src="{% static 'main/img/icon/heart.png' %}"
                                                                 alt=""></a></li>

                                            <li><a href="#"><img src="{% static 'main/img/icon/search.png' %}"
                                                                 alt=""></a></li>
                                        </ul>
                                    </div>
                                    <div class="product__item__text">
                                        <h6>{{ product.title }}</h6>
                                        <a href="#" class="add-cart">+ Add To Cart</a>
                                        <div class="rating">
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                        </div>
                                        <h5>{% if product.is_discount %}
                                            ${{ product.real_price }}
                                            &nbsp;
                                            <del class="text-secondary">${{ product.price }}</del>{% else %}
                                            ${{ product.price }}{% endif %}</h5>
                                        <div class="product__color__select">
                                            <label for="pc-4">
                                                <input type="radio" id="pc-4">
                                            </label>
                                            <label class="active black" for="pc-5">
                                                <input type="radio" id="pc-5">
                                            </label>
                                            <label class="grey" for="pc-6">
                                                <input type="radio" id="pc-6">
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    {% if page_obj.paginator.count >= 9 %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="product__pagination">
                                    {% for page in page_obj.paginator.page_range %}
                                        <a class="{% if page == page_obj.number %}active{% endif %}"
                                           href="?page={{ page }}">{{ page }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->
{% endblock %}

{% block extra_js %}
    <script>
        function addSearchParam(name, value) {
            let searchParam = new URLSearchParams(window.location.search)
            if (searchParam.has(name) && searchParam.get(name) == value) {
                searchParam.delete(name)
            } else {
                searchParam.set(name, value)
            }
            window.location.search = searchParam.toString()
        }

        $(".js-range-slider").ionRangeSlider({
            type: "double",
            grid: true,
            min: {{ min }},
            max: {{ max }},
            from: {% get_current_price request 0 %},
            to: {% get_current_price request 1 %},
            prefix: "$",
            onFinish(data) {
                addSearchParam('price', data.from.toString() + ';' + data.to.toString())
            }
        });
    </script>
{% endblock %}